// Generates src/lib/icons.generated.ts: SVG path data for every Material
// Symbols icon the web app draws (DECISIONS.md D13, D16).
//
// The category icon keys come from /shared/category-style.json (the same
// keys the phone renders with Flutter's Icons.*); the rest are UI icons. Only
// these glyphs end up in the bundle: no icon font, no third-party request,
// and no ligature text flashing before a font loads.
//
// Run after changing the icon list:  node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const here = dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)
const pkgDir = dirname(require.resolve('@material-symbols/svg-400/package.json'))
const pkgVersion = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).version

const style = JSON.parse(readFileSync(join(here, '../../shared/category-style.json'), 'utf8'))
const categoryKeys = style.iconGroups.flatMap((g) => g.icons.map((i) => i.key))

// Flutter's Icons.<name> are the filled Material Icons, so category glyphs use
// the FILL=1 variant; Icons.<name>_outlined maps to the FILL=0 one.
const filled = [
  ...categoryKeys,
  style.uncategorized.icon,
  style.transfer.icon,
  'account_balance',
  'credit_card',
  'check_circle',
  'error',
  'warning',
  'info',
  'dashboard',
  'receipt_long',
  'add_circle',
  'event_note',
  'category',
  'account_balance_wallet',
  'bar_chart',
  'settings',
  'bolt',
]
const outlined = [
  'dashboard',
  'receipt_long',
  'add_circle',
  'event_note',
  'category',
  'account_balance_wallet',
  'bar_chart',
  'settings',
  'logout',
  'wifi_off',
  'cloud_off',
  'sync',
  'check_circle',
  'error',
  'warning',
  'info',
  'delete',
  'edit',
  'close',
  'check',
  'add',
  'content_paste',
  'playlist_add',
  'chevron_left',
  'chevron_right',
  'calendar_month',
  'search',
  'filter_alt_off',
  'arrow_upward',
  'arrow_downward',
  'arrow_forward',
  'swap_horiz',
  'question_mark',
  'auto_awesome',
  'payments',
  'qr_code_2',
  'atm',
  'do_not_disturb_on',
  'refresh',
  'keyboard',
  'table_rows',
  'expand_more',
  'person',
  'lock',
  'palette',
  'label',
  'cancel',
  'done_all',
  'clear_all',
  'open_in_new',
  'expand_more',
  // Bills, reminders, reports, themes (increment 4)
  'schedule',
  'event',
  'notifications',
  'notifications_active',
  'notifications_off',
  'task_alt',
  'undo',
  'alarm',
  'table_chart',
  'trending_up',
  'radio_button_checked',
  'radio_button_unchecked',
  // CSV import/export, Windows Hello (increment 5)
  'download',
  'upload_file',
  'content_copy',
  'passkey',
  'fingerprint',
  'database',
]

// Keys are Material Icons names (what the database stores and Flutter draws).
// Material Symbols renamed a few; these point at the equivalent glyph. On the
// phone card_giftcard and redeem are the same gift-card picture too.
const SYMBOLS_NAME = {
  smartphone: 'mobile',
  card_giftcard: 'redeem',
  auto_awesome: 'star_shine',
  expand_more: 'keyboard_arrow_down',
}

function pathsOf(key, fill) {
  const name = SYMBOLS_NAME[key] ?? key
  const file = join(pkgDir, 'outlined', `${name}${fill ? '-fill' : ''}.svg`)
  let svg
  try {
    svg = readFileSync(file, 'utf8')
  } catch {
    throw new Error(`Material Symbols has no "${name}"${fill ? ' (filled)' : ''} icon for "${key}": ${file}`)
  }
  if (!svg.includes('viewBox="0 -960 960 960"')) throw new Error(`Unexpected viewBox in ${file}`)
  const d = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1])
  if (d.length === 0) throw new Error(`No path in ${file}`)
  return d.join(' ')
}

function block(names, fill) {
  return [...new Set(names)]
    .sort()
    .map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(pathsOf(n, fill))},`)
    .join('\n')
}

const out = `// GENERATED by scripts/gen-icons.mjs from @material-symbols/svg-400@${pkgVersion}
// (Google Material Symbols, Apache-2.0). Do not edit by hand.
// Path data for a 960x960 viewBox with origin (0, -960).

/** Filled (FILL=1) glyphs: category icons and filled UI icons. */
export const FILLED_ICONS: Readonly<Record<string, string>> = {
${block(filled, true)}
}

/** Outlined (FILL=0) glyphs: UI icons. */
export const OUTLINED_ICONS: Readonly<Record<string, string>> = {
${block(outlined, false)}
}
`
writeFileSync(join(here, '../src/lib/icons.generated.ts'), out.replace(/\r\n/g, '\n'))
console.log(`icons.generated.ts: ${new Set(filled).size} filled, ${new Set(outlined).size} outlined`)
