// GENERATED by tool/gen_theme_tokens.dart from /shared/theme-tokens.json.
// Do not edit by hand: change the JSON and run `dart run tool/gen_theme_tokens.dart`.

import 'package:flutter/painting.dart';

import 'theme_tokens.dart';

const String kDefaultThemeId = 'ocean';

const Color kExpenseColor = Color(0xFFC62828);
const Color kIncomeColor = Color(0xFF2E7D32);
const Color kTransferColor = Color(0xFF546E7A);
const Color kUncategorizedColor = Color(0xFFB26A00);
const Color kUncategorizedInkColor = Color(0xFF7A4A00);
const Color kCardColor = Color(0xFFFFFFFF);

const List<ThemeTokens> kThemes = [
  ThemeTokens(
    id: 'ocean',
    name: 'Ocean',
    description: 'Blue and teal',
    brand: Color(0xFF1565C0),
    onBrand: Color(0xFFFFFFFF),
    brandIndicator: Color(0xFF80CBC4),
    primary: Color(0xFF1565C0),
    primaryHover: Color(0xFF0D47A1),
    primarySoft: Color(0xFFE8F3FD),
    accent: Color(0xFF00796B),
    onAccent: Color(0xFFFFFFFF),
    accentSoft: Color(0xFFD5EFEC),
    page: Color(0xFFF3F6F9),
  ),
  ThemeTokens(
    id: 'sunset',
    name: 'Sunset',
    description: 'Blue and coral',
    brand: Color(0xFF283593),
    onBrand: Color(0xFFFFFFFF),
    brandIndicator: Color(0xFFFFAB91),
    primary: Color(0xFF303F9F),
    primaryHover: Color(0xFF1A237E),
    primarySoft: Color(0xFFF0F1FA),
    accent: Color(0xFFFF7043),
    onAccent: Color(0xFF212121),
    accentSoft: Color(0xFFFFE0D6),
    page: Color(0xFFF6F5F8),
  ),
  ThemeTokens(
    id: 'forest',
    name: 'Forest',
    description: 'Green and amber',
    brand: Color(0xFF1B5E20),
    onBrand: Color(0xFFFFFFFF),
    brandIndicator: Color(0xFFFFCA28),
    primary: Color(0xFF2E7D32),
    primaryHover: Color(0xFF1B5E20),
    primarySoft: Color(0xFFE8F5E9),
    accent: Color(0xFFFFB300),
    onAccent: Color(0xFF212121),
    accentSoft: Color(0xFFFFF0C2),
    page: Color(0xFFF3F7F3),
  ),
  ThemeTokens(
    id: 'garden',
    name: 'Garden',
    description: 'Green and rose',
    brand: Color(0xFF4E7D2E),
    onBrand: Color(0xFFFFFFFF),
    brandIndicator: Color(0xFFFFCDD2),
    primary: Color(0xFF3F6B22),
    primaryHover: Color(0xFF2F5219),
    primarySoft: Color(0xFFEEF5E6),
    accent: Color(0xFFD81B60),
    onAccent: Color(0xFFFFFFFF),
    accentSoft: Color(0xFFFBDCE7),
    page: Color(0xFFF5F8F2),
  ),
  ThemeTokens(
    id: 'sunflower',
    name: 'Sunflower',
    description: 'Yellow and orange',
    brand: Color(0xFFFBC02D),
    onBrand: Color(0xFF212121),
    brandIndicator: Color(0xFFBF360C),
    primary: Color(0xFF7A5A00),
    primaryHover: Color(0xFF5C4300),
    primarySoft: Color(0xFFFFF6D6),
    accent: Color(0xFFEF6C00),
    onAccent: Color(0xFF212121),
    accentSoft: Color(0xFFFFE3C7),
    page: Color(0xFFFAF8F1),
  ),
  ThemeTokens(
    id: 'marigold',
    name: 'Marigold',
    description: 'Yellow and plum',
    brand: Color(0xFFFFA000),
    onBrand: Color(0xFF212121),
    brandIndicator: Color(0xFF6A1B9A),
    primary: Color(0xFF8A4B00),
    primaryHover: Color(0xFF6B3A00),
    primarySoft: Color(0xFFFFF0DB),
    accent: Color(0xFF7B1FA2),
    onAccent: Color(0xFFFFFFFF),
    accentSoft: Color(0xFFF0DDF6),
    page: Color(0xFFFAF6F1),
  ),
];
