// Writes lib/core/theme_tokens.g.dart from /shared/theme-tokens.json, the
// single source of the colour themes for both apps (DECISIONS.md D22).
//
//   cd mobile
//   dart run tool/gen_theme_tokens.dart
//
// test/theme_test.dart renders the same output and fails if the committed
// file is stale.
import 'dart:convert';
import 'dart:io';

const _source = '../shared/theme-tokens.json';
const _target = 'lib/core/theme_tokens.g.dart';

const _colourFields = [
  'brand',
  'onBrand',
  'brandIndicator',
  'primary',
  'primaryHover',
  'primarySoft',
  'accent',
  'onAccent',
  'accentSoft',
  'page',
];

String _color(String hex) {
  if (!RegExp(r'^#[0-9A-Fa-f]{6}$').hasMatch(hex)) throw FormatException('Not a #RRGGBB colour: $hex');
  return 'Color(0xFF${hex.substring(1).toUpperCase()})';
}

String _string(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";

String _constName(String key) => 'k${key[0].toUpperCase()}${key.substring(1)}Color';

/// The Dart source for [json] (the decoded theme-tokens.json).
String renderThemeTokens(Map<String, dynamic> json) {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_theme_tokens.dart from /shared/theme-tokens.json.')
    ..writeln('// Do not edit by hand: change the JSON and run `dart run tool/gen_theme_tokens.dart`.')
    ..writeln()
    ..writeln("import 'package:flutter/painting.dart';")
    ..writeln()
    ..writeln("import 'theme_tokens.dart';")
    ..writeln()
    ..writeln('const String kDefaultThemeId = ${_string(json['defaultTheme'] as String)};')
    ..writeln();

  final semantic = (json['semantic'] as Map).cast<String, String>();
  for (final e in semantic.entries) {
    out.writeln('const Color ${_constName(e.key)} = ${_color(e.value)};');
  }
  out
    ..writeln()
    ..writeln('const List<ThemeTokens> kThemes = [');
  for (final theme in (json['themes'] as List).cast<Map<String, dynamic>>()) {
    out
      ..writeln('  ThemeTokens(')
      ..writeln('    id: ${_string(theme['id'] as String)},')
      ..writeln('    name: ${_string(theme['name'] as String)},')
      ..writeln('    description: ${_string(theme['description'] as String)},');
    for (final f in _colourFields) {
      out.writeln('    $f: ${_color(theme[f] as String)},');
    }
    out.writeln('  ),');
  }
  out.writeln('];');
  return out.toString();
}

void main() {
  final json = jsonDecode(File(_source).readAsStringSync()) as Map<String, dynamic>;
  File(_target).writeAsStringSync(renderThemeTokens(json));
  stdout.writeln('Wrote $_target');
}
